{
    "options": {
        "env": [
            "PROJECT_ROOT=github.com/codedbypm/jaspergify",
        ]
   },
    "steps": [
        {    
            "name": "gcr.io/cloud-builders/go",
            "args": ["install"],
            "dir": "${_WORKING_DIR}"
        },
        {
            "name": "gcr.io/cloud-builders/gcloud",
            "args": [
                "functions", 
                "deploy", "$_FUNCTION_NAME", 
                "--region=europe-west1",
                "--runtime=go113",
                "--trigger-event", "$_TRIGGER_EVENT",
                "--trigger-resource", "$_TRIGGER_RESOURCE",
            ],
            "dir": "${_WORKING_DIR}"
        }
    ]
}